### ISSUE TITLE
/spawn in the Nether puts users above the bedrock ceiling

### ISSUE THREAD

**Issue by Haggle1996** [LatvianModder/EnkiTools#1]
When a user types /spawn in the Nether, the server teleports them above the bedrock ceiling in the Nether, instead of to DIM0 spawn.

**Comment by LatvianModder** [comment]
Fixed in https://github.com/LatvianModder/EnkiTools/commit/38d1015f8c822cdbcf7dd1b6d2bc8aab51539bca
